binance:
  exchange: binance
  market_type: future
  quote: USDT
  rate_limit_delay: 0.2

telegram:
  enabled: true
  bot_token: "your_bot_token"
  chat_id: "your_chat_id"

logic:
  cooldown_minutes: 30
  volume_lookback: 10
  range_lookback: 5
  debug: true   # <<< DEBUG MODE ON/OFF
